# Generated by Django 6.0.1 on 2026-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
    ]
